sonar.projectKey=taskboard
sonar.projectName=TaskBoard
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,terraform/**,terraform-jenkins/**,k8s/**
