sonar.projectKey=taskboard
sonar.projectName=taskboard

sonar.sources=src
sonar.tests=test

sonar.test.inclusions=test/**/*.js

sonar.exclusions=node_modules/**,coverage/**,k8s/**,terraform/**,terraform-jenkins/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
